# Site
name: "Dani &amp; Pojaco Blog"
title: "Dani &amp; Pojaco Blog"
description: "Un blog di due impacciati che viaggiano, provano cibo e tentano di recensire ristoranti"
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: '/'
google_analytics: ""
disqus: ""
mailchimp-list: false
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  jacopo:
    name: Jacopo
    display_name: Pojaco
    avatar: 'https://avatars.githubusercontent.com/u/32840785'
    description: "Un timido ragazzo impacciato. Lavora come sviluppatore software. ISTJ. Buon gustaio"
  daniela:
    name: Daniela
    display_name: Dani
    avatar: '/assets/images/avatar.png'
    description: "Una *piccola* ragazza impacciata. Buon gustaia."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: false
adsense-data-ad-slot: false

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
